_wandb:
    value:
        cli_version: 0.23.0
        e:
            ee5rp700vjoqzbwbldn4y0gp3vs5komm:
                args:
                    - --stage
                    - full
                    - --steps
                    - "5000"
                    - --batch-size
                    - "32"
                    - --wandb
                    - --wandb-project
                    - hoyo_motion
                codePath: hoyo_v1_1/models/train_motionclip_joint.py
                codePathLocal: hoyo_v1_1/models/train_motionclip_joint.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1967317549056"
                        used: "625312251904"
                email: jouta15123@gmail.com
                executable: /home/jouta/venvs/motionclip/bin/python
                git:
                    commit: e0c979886c4de2af3accdad08a3d14931b5f6fdf
                    remote: git@github.com:jouta15123/NaVILA-Bench-for5090.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-23b2d92b-cbcd-c594-edf7-6131c8c31f37
                host: jouta-FRONTIER
                memory:
                    total: "66995527680"
                os: Linux-6.8.0-85-generic-x86_64-with-glibc2.35
                program: /home/jouta/NaVILA-Bench/hoyo_v1_1/models/train_motionclip_joint.py
                python: CPython 3.11.14
                root: /home/jouta/NaVILA-Bench
                startedAt: "2025-11-23T04:18:31.413130Z"
                writerId: ee5rp700vjoqzbwbldn4y0gp3vs5komm
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 75
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 75
            "3":
                - 2
                - 16
                - 61
            "4": 3.11.14
            "5": 0.23.0
            "6": 4.57.1
            "12": 0.23.0
            "13": linux-x86_64
batch_size:
    value: 32
device:
    value: cuda
lambda_contrastive:
    value: 0.1
lr:
    value: 1e-05
lr_decoder:
    value: 1e-05
lr_encoder:
    value: 1e-05
stage:
    value: full
steps:
    value: 5000
target_len:
    value: 60
