_wandb:
    value:
        cli_version: 0.23.0
        e:
            0l5t60x6cqz800nek9jmop63ualeec1x:
                args:
                    - --steps
                    - "3000"
                    - --samples-per-label
                    - "4"
                    - --hidden-dim
                    - "256"
                    - --latent-dim
                    - "256"
                    - --wandb
                codePath: hoyo_v1_1/models/train_motion_scratch.py
                codePathLocal: hoyo_v1_1/models/train_motion_scratch.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1967317549056"
                        used: "625310580736"
                email: jouta15123@gmail.com
                executable: /home/jouta/venvs/motionclip/bin/python
                git:
                    commit: e0c979886c4de2af3accdad08a3d14931b5f6fdf
                    remote: git@github.com:jouta15123/NaVILA-Bench-for5090.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-23b2d92b-cbcd-c594-edf7-6131c8c31f37
                host: jouta-FRONTIER
                memory:
                    total: "66995527680"
                os: Linux-6.8.0-85-generic-x86_64-with-glibc2.35
                program: /home/jouta/NaVILA-Bench/hoyo_v1_1/models/train_motion_scratch.py
                python: CPython 3.11.14
                root: /home/jouta/NaVILA-Bench
                startedAt: "2025-11-20T07:41:53.980916Z"
                writerId: 0l5t60x6cqz800nek9jmop63ualeec1x
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 75
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 75
            "3":
                - 2
                - 16
                - 61
            "4": 3.11.14
            "5": 0.23.0
            "6": 4.57.1
            "12": 0.23.0
            "13": linux-x86_64
device:
    value: cuda
hidden_dim:
    value: 256
latent_dim:
    value: 256
lr:
    value: 0.001
lr_encoder:
    value: 0.0001
samples_per_label:
    value: 4
steps:
    value: 3000
temp:
    value: 0.07
train_encoder:
    value: true
